#!/bin/sh

if [[ -f apps.tar.gz ]]; then
  # NOTE: it will be required for Cockpit as mount point, it should be empty
  mkdir -p /cloud

  cp apps.tar.gz /root/

  # NOTE: it's not enabled to allow user use Cockpit to attach disk.
  # Then user should start this service.
  # ENABLE_SERVICES="$ENABLE_SERVICES home_cloud_init.service"

  cp files/home_cloud_init.service /etc/systemd/system/

  # combustion can be on fat filesystem without proper file permissions
  chmod 644 /etc/systemd/system/home_cloud_init.service
fi
