#!/bin/sh
# Automatically poweroff daily

ENABLE_SERVICES="$ENABLE_SERVICES poweroff.timer"

cp files/poweroff.timer /etc/systemd/system/
cp files/poweroff.service /etc/systemd/system/

# combustion can be on fat filesystem without proper file permissions
chmod 644 /etc/systemd/system/poweroff.timer
chmod 644 /etc/systemd/system/poweroff.service
