#!/bin/sh

ENABLE_SERVICES="$ENABLE_SERVICES firstboot_poweroff.service"

cp files/firstboot_poweroff.service /etc/systemd/system/

# combustion can be on fat filesystem without proper file permissions
chmod 644 /etc/systemd/system/firstboot_poweroff.service
